BEGIN;

CREATE TABLE USERS (
    U_ID SERIAL PRIMARY KEY,
    U_NAME VARCHAR(50) NOT NULL,
    U_MAIL VARCHAR(72) NOT NULL, -- 72 is the maximum input length for BCrypt
    U_TYPE INT NOT NULL
);

CREATE TABLE USER_CREDENTIALS (
    -- Bcrypt has an output of 60 bytes
    UMAIL_HASH BYTEA NOT NULL PRIMARY KEY,
    UPASS_HASH BYTEA NOT NULL
);

CREATE TABLE USER_TYPES (
    UT_ID SERIAL PRIMARY KEY,
    UT_NAME VARCHAR(50) NOT NULL,
    UT_PERMISSIONS JSONB NOT NULL -- binary json
);

CREATE TABLE CATEGORIES (
    C_ID SERIAL PRIMARY KEY,
    C_NAME VARCHAR(50) NOT NULL,
    C_DESCRIPTION TEXT,
    PC_ID INT
);

CREATE TABLE PRODUCTS (
    P_ID SERIAL PRIMARY KEY,
    P_NAME VARCHAR(100) NOT NULL,
    P_MANUFACTURER VARCHAR(100),
    P_DESCRIPTION TEXT,
    P_PRICE DECIMAL(10, 2) NOT NULL,
    P_IMAGE VARCHAR(255),
    P_QUANTITY INT NOT NULL,
    C_ID INT
);

ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (C_ID) REFERENCES CATEGORIES(C_ID);

CREATE TABLE SHOPPING_CARTS (
    SC_ID SERIAL PRIMARY KEY,
    U_ID INT NOT NULL
);

ALTER TABLE SHOPPING_CARTS ADD CONSTRAINT FK_SHOPPING_CARTS_USER FOREIGN KEY (U_ID) REFERENCES USERS(U_ID);

CREATE TABLE SHOPPING_CART_ITEMS (
    SCI_ID SERIAL PRIMARY KEY,
    SC_ID INT NOT NULL,
    P_ID INT NOT NULL,
    SCI_QUANTITY INT NOT NULL
);

ALTER TABLE SHOPPING_CART_ITEMS ADD CONSTRAINT FK_SHOPPING_CART_ITEMS_CART FOREIGN KEY (SC_ID) REFERENCES SHOPPING_CARTS(SC_ID), ADD CONSTRAINT FK_SHOPPING_CART_ITEMS_PRODUCT FOREIGN KEY (P_ID) REFERENCES PRODUCTS(P_ID);

CREATE TABLE ORDERS (
    O_ID SERIAL PRIMARY KEY,
    U_ID INT NOT NULL,
    O_DATE TIMESTAMP NOT NULL,
    O_PRICE DECIMAL(10, 2) NOT NULL,
    O_STATUS VARCHAR(20),
    O_ADDRESS_LINE VARCHAR(255),
    O_CITY VARCHAR(100),
    O_POSTAL_CODE VARCHAR(20),
    O_COUNTRY VARCHAR(100)
);

ALTER TABLE ORDERS ADD CONSTRAINT FK_ORDERS_USER FOREIGN KEY (U_ID) REFERENCES USERS(U_ID);

CREATE TABLE ORDER_ITEMS (
    OI_ID SERIAL PRIMARY KEY,
    O_ID INT NOT NULL,
    P_ID INT NOT NULL,
    O_QUANTITY INT NOT NULL,
    O_PRICE DECIMAL(10, 2) NOT NULL
);

ALTER TABLE ORDER_ITEMS ADD CONSTRAINT FK_ORDER_ITEMS_ORDER FOREIGN KEY (O_ID) REFERENCES ORDERS(O_ID), ADD CONSTRAINT FK_ORDER_ITEMS_PRODUCT FOREIGN KEY (P_ID) REFERENCES PRODUCTS(P_ID);

INSERT INTO USER_TYPES (UT_NAME, UT_PERMISSIONS) VALUES 
('ADMIN', '["GODMODE"]'),
('CUSTOMER', '{}');

INSERT INTO CATEGORIES (C_NAME, C_DESCRIPTION, PC_ID) VALUES
('Laptops', 'Portable computers', NULL),
('Desktops', 'Personal computers for regular use', NULL),
('Monitors', 'Display screens for computers', NULL),
('Keyboards', 'Input devices for typing', NULL),
('Mice', 'Input devices for pointing and clicking', NULL),
('Printers', 'Devices for printing documents', NULL),
('Storage', 'Devices for storing data', NULL),
('Networking', 'Devices for network connectivity', NULL),
('Accessories', 'Various computer accessories', NULL),
('Software', 'Computer programs and applications', NULL);

COMMIT;